# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-31 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moves',
            old_name='black',
            new_name='move',
        ),
        migrations.RemoveField(
            model_name='moves',
            name='white',
        ),
    ]
