# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-01 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_filehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='filehistory',
            name='checksum',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
