# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-01 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_filehistory_checksum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='round',
            field=models.FloatField(null=True),
        ),
    ]
